version = 1

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"
  max_line_length = 999

[[transformers]]
name = "autopep8"

[[transformers]]
name = "black"

[[transformers]]
name = "isort"

[[transformers]]
name = "ruff"

[[transformers]]
name = "yapf"
