["Recipe Runner"]
regex = 'a href="(\S*)" class="wpp-post-title" target="_self"'
entree_page_url = 'https://www.reciperunner.com/category/recipes/dinners/'
side_page_url = 'https://reciperunner.com/category/recipes/side-dishes/'

["Paleo Running Momma"]
regex = 'a class="entry-title-link" rel="bookmark" href="(\S*)"'
entree_page_url = 'https://www.paleorunningmomma.com/course/dinner/'
side_page_url = 'https://www.paleorunningmomma.com/course/veggies-sides/'

["Skinny Taste"]
regex = 'h3 class="entry-title(?: ast-blog-single-element)*"><a href="(\S*)"(?: rel="bookmark")*'
entree_page_url = 'https://www.skinnytaste.com/recipes/dinner-recipes/'
side_page_url = 'https://www.skinnytaste.com/recipes/side-dishes/'

["Two Peas and Their Pod"]
regex = '<p class="entry-category">(?!Breakfast\\/Brunch).*?<\\/p><h2 class="post-summary__title"><a href="(\S*)"'
entree_page_url = 'https://www.twopeasandtheirpod.com/category/recipes/main-dishes/'
side_page_url = 'https://www.twopeasandtheirpod.com/category/recipes/side/'

["Well Plated"]
regex = 'h2 class="post-summary__title"><a href="(\S*)"'
entree_page_url = 'https://www.wellplated.com/category/recipes-by-type/entreesmain-dishes/#recent'
side_page_url = 'https://www.wellplated.com/category/recipes-by-type/side-dishes-recipe-type/#recent'

["The Spruce Eats"]
regex = 'a.*class="comp mntl-card-list-items mntl-document-card mntl-card card card--no-image".*href="(\S*)"'
entree_page_url = 'https://www.thespruceeats.com/dinner-4162806'
side_page_url = 'https://www.thespruceeats.com/side-dishes-4162722'

["Nourished By Nutrition"]
regex = 'a class="post" href="(\S*)"'
entree_page_url = 'https://nourishedbynutrition.com/recipe-index/?_sft_category=entrees'
side_page_url = 'https://nourishedbynutrition.com/category/recipes/sides/'

["Eating Bird Food"]
regex = 'h2 class="post-summary__title"><a href="(\S*)"'
entree_page_url = 'https://www.eatingbirdfood.com/category/meal-type/dinnerlunch/'
side_page_url = 'https://www.eatingbirdfood.com/category/meal-type/dinnerlunch/sides/'

["Budget Bytes"]
regex = 'article class="post-summary post-summary--\S*"><a href="(\S*)" aria-label='
entree_page_url = 'https://www.budgetbytes.com/category/recipes/?fwp_by_course=main-dish'
side_page_url = 'https://www.budgetbytes.com/category/recipes/side-dish/'

["Lean and Green Recipes"]
regex = 'h2 class="recipe-card-title"><a href="(\S*)"'
entree_page_url = 'https://www.leanandgreenrecipes.net/recipes/category/main-course/'
side_page_url = 'https://www.leanandgreenrecipes.net/recipes/category/accompaniment/'

["Minimalist Baker"]
regex = 'h3 class="post-summary__title"><a href="(\S*)"'
entree_page_url = 'https://www.minimalistbaker.com/recipe-index/?fwp_recipe-type=entree'
side_page_url = 'https://www.minimalistbaker.com/recipe-index/?fwp_recipe-type=salad'

["Gimme Some Oven"]
regex = 'a href="(\S*)" rel="bookmark" title="'
entree_page_url = 'https://www.gimmesomeoven.com/all-recipes/?fwp_course=main-course'
side_page_url = 'https://www.gimmesomeoven.com/all-recipes/?fwp_course=side-dishes'

["Half Baked Harvest"]
regex = 'h2 class="post-summary__title"><a href="(\S*)"'
entree_page_url = 'https://www.halfbakedharvest.com/category/recipes/type-of-meal/main-course/'
side_page_url = 'https://www.halfbakedharvest.com/category/recipes/type-of-meal/side-dishesvegetables/'

["Pinch of Yum"]
regex = '<a class="block md:hover:opacity-60 space-y-2 flex flex-col" href="(\S*)">'
entree_page_url = 'https://pinchofyum.com/recipes/dinner'
side_page_url = 'https://pinchofyum.com/recipes/salad'

["Heather Christo"]
regex = '<div class="title-label post">Recipe<\\/div>\\s*<a href="(\S*)"'
entree_page_url = 'https://heatherchristo.com/category/recipes/?cat=10533&orderby=date'
side_page_url = 'https://heatherchristo.com/category/recipes/?cat=200&orderby=date'

["Fit Slow Cooker Queen"]
regex = 'a href="(\S*)" class="excerpt-link" title=".*"><figure class="post-thumbnail"'
entree_page_url = 'https://fitslowcookerqueen.com/category/slowcooker/'
side_page_url = 'https://fitslowcookerqueen.com/category/salads/'

["Eat Live Run"]
regex = 'div class="post-img">\\s*<a href="(\S*)"'
entree_page_url = 'https://www.eatliverun.com/category/recipes-2/main-course-2/'
side_page_url = 'https://www.eatliverun.com/category/recipes-2/side-dishes/'
